added rules from trucknet-io project
trucknet-io/tslint-config-trucknet-io pull request #5
Opened 2019-09-26 08:41 UTC by lunevav

2019-09-26 14:45 UTC, goooseman requested changes

2019-09-26 14:45 UTC, goooseman commented on tslint.json
> +    "max-line-length": [
max-line-length все таки стоит наверное выключить

ибо этим занят prettier

2019-10-02 08:39 UTC, lunevav commented on tslint.json
> +    "max-line-length": [
done

2019-10-02 08:42 UTC, goooseman approved these changes

2019-10-02 08:42 UTC, merged